### ISSUE TITLE
Container registry not recognized

### ISSUE THREAD

**Issue by spijker** [texano00/urunner#16]
Running harbor 
I added the following in a value 
````
affinity: {}
config:
  URUNNER_CONF_CONTAINER_REGISTRY_TO_WATCH: registry.harbor
  URUNNER_CONF_CONTAINER_REGISTRY_TYPE: harbor
  URUNNER_CONF_FREQUENCY_CHECK_SECONDS: 20
  URUNNER_CONF_LOG_LEVEL: DEBUG
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/texano00/urunner
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
resources: {}
secret:
  harbor:
    password: versysecret
    username: "robot-urunner"
  secretName: "secret-urunner"
securityContext: {}
serviceAccount:
  annotations: {}
  create: true
  name: ""
tolerations: []
````
I get always this error :

````
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Name: mapineq-pgtileserv
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Image: Image(image_id='mapineq-mapineq-pgtileserv-pramsey/pg_tileserv-latest', namespace='mapineq', resource='mapineq-pgtileserv', image='pramsey/pg_tileserv', tag='latest', tag_digest='')
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Container registry not recognized
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Name: mapineq-pgfeatureserv
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Image: Image(image_id='mapineq-mapineq-pgfeatureserv-pramsey/pg_featureserv-latest', namespace='mapineq', resource='mapineq-pgfeatureserv', image='pramsey/pg_featureserv', tag='latest', tag_dige
st='')
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Container registry not recognized
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Name: mapineqfrontend
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Image: Image(image_id='mapineq-mapineqfrontend-registry.harbor/mapineq/mapineqfrontend:latest-latest', namespace='mapineq', resource='mapineqfrontend', image='registry.harbor/mapineq/mapineqfrontend:latest', tag='latest', tag_digest='')
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:Image(image_id='mapineq-mapineqfrontend-registry.harbor/mapineq/mapineqfrontend:latest-latest', namespace='mapineq', resource='mapineqfrontend', image='registry.harbor/mapineq/mapineqfrontend:latest', tag='latest', tag_digest='')
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:('mapineq/mapineqfrontend', 'latest')
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:mapineq/mapineqfrontend
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:<Response [401]>
urunner-6c7d4967fd-2ksdk urunner ERROR:root:Error status code: 401
urunner-6c7d4967fd-2ksdk urunner DEBUG:root:<Response [401]>
````

**Comment by spijker** [comment]
Still the same , with all permissions
````
Login Succeeded
~@docker:~# docker pull registry.harbor/mapineq/mapineqfrontend
Using default tag: latest
latest: Pulling from mapineq/mapineqfrontend
c6a83fedfae6: Pull complete 
7f5898476db7: Pull complete 
45f552c78c31: Pull complete 
62a896bb4a21: Extracting [==================================================>]     955B/955B
532b9a30583c: Download complete 
41c49cbde6a6: Download complete 
9da224fdd412: Download complete 
35b039ba2bc5: Downloading [====>                                              ]  1.179MB/13.19MB
ad5741a9e700: Download complete 
f69542233232: Download complete 
````

````
urunner-556df4b545-7fkhh urunner 
urunner-556df4b545-7fkhh urunner DEBUG:root:Name: mapineq-pgtileserv
urunner-556df4b545-7fkhh urunner DEBUG:root:Image: Image(image_id='mapineq-mapineq-pgtileserv-pramsey/pg_tileserv-latest', namespace='mapineq', resource='mapineq-pgtileserv', image='pramsey/pg_tileserv', tag='latest', tag_digest='')
urunner-556df4b545-7fkhh urunner DEBUG:root:Container registry not recognized
urunner-556df4b545-7fkhh urunner DEBUG:root:Name: mapineqfrontend
urunner-556df4b545-7fkhh urunner DEBUG:root:Image: Image(image_id='mapineq-mapineqfrontend-registry.harbor/mapineq/mapineqfrontend:latest-latest', namespace='mapineq', resource='mapineqfrontend', image='registry.webhosting.rug.
nl/mapineq/mapineqfrontend:latest', tag='latest', tag_digest='')
urunner-556df4b545-7fkhh urunner DEBUG:root:Image(image_id='mapineq-mapineqfrontend-registry.harbor/mapineq/mapineqfrontend:latest-latest', namespace='mapineq', resource='mapineqfrontend', image='registry.harbor/mapi
neq/mapineqfrontend:latest', tag='latest', tag_digest='')
urunner-556df4b545-7fkhh urunner DEBUG:root:('mapineq/mapineqfrontend', 'latest')
urunner-556df4b545-7fkhh urunner DEBUG:root:mapineq/mapineqfrontend
urunner-556df4b545-7fkhh urunner DEBUG:root:<Response [401]>
urunner-556df4b545-7fkhh urunner ERROR:root:Error status code: 401
urunner-556df4b545-7fkhh urunner DEBUG:root:<Response [401]>
urunner-556df4b545-7fkhh urunner DEBUG:root:Name: mapineq-pgfeatureserv
urunner-556df4b545-7fkhh urunner DEBUG:root:Image: Image(image_id='mapineq-mapineq-pgfeatureserv-pramsey/pg_featureserv-latest', namespace='mapineq', resource='mapineq-pgfeatureserv', image='pramsey/pg_featureserv', tag='latest', tag_dige
st='')
urunner-556df4b545-7fkhh urunner DEBUG:root:Container registry not recognized
````
Is the problem not in :latest-latest ?
registry.harbor/mapineq/mapineqfrontend:latest-latest

**Comment by texano00** [comment]
Hi @spijker,
have you tried to remove the double quotes from your helm values `secret.harbor.username` ?

```
secret:
  harbor:
    password: versysecret
    username: robot-urunner
    # username: "robot-urunner" <-- old one
```

Please have a look also of what's inside the secret of URunner through
`kubectl describe secret secret-urunner -n <urunner-namespace>`
